# This is a basic workflow to help you get started with Actions

name: deploy vps

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: SetUp Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
        
      
      - run: npm install @vue/cli
      - run: cd website ; npm install ; npm run build

      - name: Generate ssh key
        run: echo "$SSH_KEYS" > key && chmod 600 key
        env:
          SSH_KEYS: ${{ secrets.SSH_KEYS }}
      - name: Deploy
        run: rsync -auzrv --delete --exclude ".git/" -e "ssh -i ./key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p ${SSH_PORT}" dist/ $SSH_USER@$SSH_HOST:$DEPLOY_PATH
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: SetUp git repogitories
        env: 
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          echo "$DEPLOY_KEY" > ~/deploy_key.pem
          chmod 600 ~/deploy_key.pem
          git config --global user.email "tukuyo.dayo@gmail"
          git config --global user.name "tukuyo"
          cd dist
          git config remote.origin.url "git@github.com:tukuyo/tukuyo.github.io.git"
          git checkout master

      - name: deploy pages
        env: 
          GIT_SSH_COMMAND: ssh -i ~/deploy_key.pem -o StrictHostKeyChecking=no -F /dev/null
        run: |
          cd dist
          git add -A
          if ! git diff -- cached --quiet; then
            git commit -m "Deploy $GITHUB_SHA by Github Actions"
            git pull origin master
            git push origin master
          fi


